version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2021-01-01 to 2021-12-31 by month"
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_measures:
    run: cohortextractor:latest generate_measures
        --study-definition study_definition
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        measure: output/measure_*.csv

  generate_deciles_charts:
    run: deciles-charts:v0.0.33
        --input-files output/measure_*.csv
        --output-dir output/figures
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        deciles_charts: output/figures/deciles_*_*.*
  
  generate_summaries:
    run: python:latest python analysis/summarise.py
    needs: [generate_measures]
    outputs:
      moderately_sensitive:
        measure_totals: output/tables/measure_*_total.csv
        overall_summary: output/tables/overall_summary.csv

